import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "../styles/globals.css";
import Footer from "@/components/common/Footer";
import FloatingButton from "@/components/common/FloatingButton";
import { usePathname } from "next/navigation";
import { RecoilRoot, useRecoilValue } from "recoil";
import ClientProvider from "./clientProvider";
import NavModal from "@/components/common/NavModal";
import Script from "next/script";
import Loading from "@/components/common/LoadingSpinner";

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ["latin"], // 또는 preload: false
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900"], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

export const metadata: Metadata = {
  title: "제핏",
  // description: "Generated by create next app",
  icons: { icon: "/zefit.png", apple: "/zefit.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body className={notoSansKr.className}>
        <ClientProvider>
          <FloatingButton />
          <Loading />
          <main>
            {children}
          </main>
          <Footer />
          <Script
            src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_KEY}&libraries=services&autoload=false`}
            strategy="lazyOnload" // 페이지 로드 이후 스크립트 로드
          />
        </ClientProvider>
      </body>
    </html>
  );
}
